name: Publish to VS Code Extensions Marketplace

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/workflows/release.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Install vsce
        run: npm install --global @vscode/vsce

      - name: Package VSIX
        run: vsce package

      - name: Publish to Marketplace
        run: vsce publish -p ${{ secrets.MS_AZURE_PAT }}
        env:
          PUBLISHER_ID: chatIDE
